<?php

namespace App\Http\Controllers;

use Illuminate\Support\Arr;

class MainController extends Controller
{
    public function index()
    {
        $produks = [
            [
                'id_produk' => 1,
                'nama_produk' => 'Sofa',
                'kuantitas' => 3,
                'panjang' => 200,
                'lebar' => 90,
                'deskripsi' => 'Elegant sofa with a modern design. Ideal for a stylish living room.',
                'date_of_creation' => '2023-11-01',
            ],
            [
                'id_produk' => 2,
                'nama_produk' => 'Dining Table',
                'kuantitas' => 2,
                'panjang' => 150,
                'lebar' => 90,
                'deskripsi' => 'High-quality materials for a long-lasting look.',
                'date_of_creation' => '2023-11-02',
            ],
            [
                'id_produk' => 3,
                'nama_produk' => 'Chair',
                'kuantitas' => 6,
                'panjang' => 50,
                'lebar' => 45,
                'deskripsi' => 'It strikes the perfect balance between comfort and sleek design.',
                'date_of_creation' => '2023-11-03',
            ],
            [
                'id_produk' => 4,
                'nama_produk' => 'Bedding',
                'kuantitas' => 3,
                'panjang' => 180,
                'lebar' => 160,
                'deskripsi' => 'Equipped with an elegant headboard to add a touch of luxury in the bedroom.',
                'date_of_creation' => '2023-11-04',
            ],
            [
                'id_produk' => 5,
                'nama_produk' => 'Wardrobe',
                'kuantitas' => 4,
                'panjang' => 120,
                'lebar' => 60,
                'deskripsi' => 'Spacious storage for clothes and accessories in a trendy style.',
                'date_of_creation' => '2023-11-05',
            ],
            [
                'id_produk' => 6,
                'nama_produk' => 'Workbench',
                'kuantitas' => 4,
                'panjang' => 120,
                'lebar' => 70,
                'deskripsi' => 'Designed to increase productivity and provide a stylish workspace.',
                'date_of_creation' => '2023-11-06',
            ],
            [
                'id_produk' => 7,
                'nama_produk' => 'Console Table',
                'kuantitas' => 6,
                'panjang' => 100,
                'lebar' => 30,
                'deskripsi' => 'Perfect for displaying decorations or as a finishing touch in the hallway.',
                'date_of_creation' => '2023-11-07',
            ],
            [
                'id_produk' => 8,
                'nama_produk' => 'Coffee Table',
                'kuantitas' => 6,
                'panjang' => 80,
                'lebar' => 50,
                'deskripsi' => 'Creates the perfect centerpiece for a living room or sitting area.',
                'date_of_creation' => '2023-11-08',
            ],
            [
                'id_produk' => 9,
                'nama_produk' => 'Sideboard',
                'kuantitas' => 7,
                'panjang' => 140,
                'lebar' => 60,
                'deskripsi' => 'Provides additional storage while adding a touch of luxury to the dining area.',
                'date_of_creation' => '2023-11-09',
            ],
            [
                'id_produk' => 10,
                'nama_produk' => 'Bookshelf',
                'kuantitas' => 4,
                'panjang' => 100,
                'lebar' => 25,
                'deskripsi' => 'Creates an organized and modern look for your book collection.',
                'date_of_creation' => '2023-11-10',
            ],
            [
                'id_produk' => 11,
                'nama_produk' => 'TV cabinet',
                'kuantitas' => 4,
                'panjang' => 160,
                'lebar' => 40,
                'deskripsi' => 'Provides the perfect place to place media devices and decorative accents.',
                'date_of_creation' => '2023-11-11',
            ],
            [
                'id_produk' => 12,
                'nama_produk' => 'Folding Mattress',
                'kuantitas' => 3,
                'panjang' => 180,
                'lebar' => 120,
                'deskripsi' => 'Suitable for the living room or guest room, providing additional sleeping comfort.',
                'date_of_creation' => '2023-11-12',
            ],
            [
                'id_produk' => 13,
                'nama_produk' => 'Lounge Chair',
                'kuantitas' => 5,
                'panjang' => 80,
                'lebar' => 100,
                'deskripsi' => 'Designed for maximum relaxation after a long day.',
                'date_of_creation' => '2023-11-13',
            ],
            [
                'id_produk' => 14,
                'nama_produk' => 'Rocking Chair',
                'kuantitas' => 2,
                'panjang' => 750,
                'lebar' => 650,
                'deskripsi' => 'Provides a sense of nostalgia and comfort in one design.',
                'date_of_creation' => '2023-11-14',
            ],
            [
                'id_produk' => 15,
                'nama_produk' => 'Dressing Table',
                'kuantitas' => 6,
                'panjang' => 70,
                'lebar' => 60,
                'deskripsi' => 'It features a mirror and ample storage for beauty tools.',
                'date_of_creation' => '2023-11-15',
            ],
            [
                'id_produk' => 16,
                'nama_produk' => 'Shoe Rack',
                'kuantitas' => 7,
                'panjang' => 80,
                'lebar' => 30,
                'deskripsi' => 'Helps maintain order and cleanliness in the sleeping area or hallway.',
                'date_of_creation' => '2023-11-16',
            ],
            [
                'id_produk' => 17,
                'nama_produk' => 'Bar Stools',
                'kuantitas' => 4,
                'panjang' => 40,
                'lebar' => 40,
                'deskripsi' => 'Provides a trendy touch of style for the entertainment room or kitchen.',
                'date_of_creation' => '2023-11-17',
            ],
            [
                'id_produk' => 18,
                'nama_produk' => 'Kitchen Cabinets',
                'kuantitas' => 6,
                'panjang' => 120,
                'lebar' => 80,
                'deskripsi' => 'Offers optimal storage for kitchen utensils and tableware.',
                'date_of_creation' => '2023-11-18',
            ],
            [
                'id_produk' => 19,
                'nama_produk' => 'Kids Study Desk',
                'kuantitas' => 8,
                'panjang' => 100,
                'lebar' => 60,
                'deskripsi' => 'Create a fun and functional learning space.',
                'date_of_creation' => '2023-11-19',
            ],
            [
                'id_produk' => 20,
                'nama_produk' => 'Wall Shelf',
                'kuantitas' => 6,
                'panjang' => 60,
                'lebar' => 20,
                'deskripsi' => 'Ideal for storing books, decorations or small collections in a minimalist style.',
                'date_of_creation' => '2023-11-20',
            ],
        ];
        return view('main', compact('produks'));
    }
}


